# Generated by Django 4.0.1 on 2022-01-12 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='residence',
            table='residences',
        ),
        migrations.AlterModelTable(
            name='size',
            table='sizes',
        ),
        migrations.AlterModelTable(
            name='space',
            table='spaces',
        ),
        migrations.AlterModelTable(
            name='style',
            table='styles',
        ),
    ]
