# Generated by Django 4.0.1 on 2022-01-12 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0002_alter_residence_table_alter_size_table_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posting',
            name='name',
        ),
        migrations.AddField(
            model_name='posting',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='posting',
            name='content',
            field=models.TextField(max_length=1500, null=True),
        ),
        migrations.AlterField(
            model_name='posting',
            name='tags',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
