# Generated by Django 4.0.1 on 2022-01-12 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kakao_id', models.IntegerField(unique=True)),
                ('email', models.CharField(max_length=150, null=True)),
                ('nickname', models.CharField(max_length=50)),
                ('profile_image_url', models.URLField(max_length=2000)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
